export const taxType = [{value: 1, text: 'Consumidor final'}, {value: 2, text: 'Exento'}, {value: 3, text: 'Exterior'}, {value: 4, text: 'IVA no alcanzado'}, {value: 5, text: 'Monotributista'}, {value: 6, text: 'Responsable inscripto'}]
export const idType = [{value: 1, text: 'Sin identificar / venta global diaria'}, {value: 2, text: 'DNI'}, {value: 3, text: 'CUIL'}, {value: 4, text: 'CUIT'}]
export const shippingType = [{value: 1, text: 'Importación'}, {value: 2, text: 'Exportación'}, {value: 3, text: 'Doméstico'}]
export const serviceType = [{value: 1, text: 'Doméstico'}, {value: 2, text: 'Economy'}, {value: 3, text: 'Priority'}]
export const packageType = [{value: 1, text: 'Cajas'}, {value: 2, text: 'Pack'}, {value: 3, text: 'Sobre'}]
export const shippingZone = ['1', '2', '3', '4', '5', '6']
