import countriesList from './countries.json'
import argProvincesList from './arg_provinces.json'
export const taxCategories = [{value: 3, text: 'Consumidor Final'}, {value: 5, text: 'Exento'}, {value: 6, text: 'Exterior'}, {value: 7, text: 'IVA No Alcanzado'}, {value: 4, text: 'Monotributista'}, {value: 1, text: 'Responsable Inscripto'}]
export const docTypes = [{value: 41, text: 'Acta nacimiento'}, {value: 36, text: 'CDI'}, {value: 45, text: 'Certificado de Migración'}, {value: 43, text: 'CI Bs. As. RNP'}, {value: 12, text: 'CI Buenos Aires'}, {value: 13, text: 'CI Catamarca'}, {value: 26, text: 'CI Chaco'}, {value: 27, text: 'CI Chubut'}, {value: 14, text: 'CI Córdoba'}, {value: 15, text: 'CI Corrientes'}, {value: 16, text: 'CI Entre Ríos'}, {value: 39, text: 'CI Extranjera'}, {value: 28, text: 'CI Formosa'}, {value: 17, text: 'CI Jujuy'}, {value: 31, text: 'CI La Pampa'}, {value: 19, text: 'CI La Rioja'}, {value: 18, text: 'CI Mendoza'}, {value: 29, text: 'CI Misiones'}, {value: 30, text: 'CI Neuquén'}, {value: 11, text: 'CI Policía Federal'}, {value: 32, text: 'CI Río Negro'}, {value: 20, text: 'CI Salta'}, {value: 21, text: 'CI San Juan'}, {value: 22, text: 'CI San Luis'}, {value: 33, text: 'CI Santa Cruz'}, {value: 23, text: 'CI Santa Fe'}, {value: 24, text: 'CI Santiago del Estero'}, {value: 34, text: 'CI Tierra del Fuego'}, {value: 25, text: 'CI Tucumán'}, {value: 35, text: 'CUIL'}, {value: 9, text: 'CUIT'}, {value: 10, text: 'DNI'}, {value: 40, text: 'En trámite'}, {value: 38, text: 'LC'}, {value: 37, text: 'LE'}, {value: 42, text: 'Pasaporte'}, {value: 44, text: 'Sin identificar/venta global diaria'}, {value: 46, text: 'Usado por Anses para Padrón'}]
export const shippingTypes = [{value: 1, text: 'Importación'}, {value: 2, text: 'Exportación'}, {value: 3, text: 'Doméstico'}]
export const serviceTypes = [{value: 1, text: 'Doméstico'}, {value: 2, text: 'Economy'}, {value: 3, text: 'Priority'}]
export const packageTypes = [{value: 1, text: 'Caja'}, {value: 2, text: 'Pack'}, {value: 3, text: 'Sobre'}]
export const shippingZones = [{value: 1, text: '1'}, {value: 2, text: '2'}, {value: 3, text: '3'}, {value: 4, text: '4'}, {value: 5, text: '5'}, {value: 6, text: '6'}]
export const countries = countriesList
export const argProvinces = argProvincesList
